# Use root/example as user/password credential
version: '3.8'

services:
  mysql:
    image: mysql:latest
    #container_name: mysql
    #command: --default-authentification-plugin=mysql_native_password
    restart: always
    environment:
       #MYSQL_USER: robson
      MYSQL_ROOT_PASSWORD: post
      #MYSQL_PASSWORD: post
      #MYSQL_DATABASE: projetdb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
     #container_name: phpmyadmin
     image: phpmyadmin/phpmyadmin:latest
     environment:
      #MYSQL_ROOT_PASSWORD: post
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
     ports:
      - "8080:80"

volumes:
  mysql-data:

